---
  - name: Kali | Xhosts access control disabled
    shell: echo "xhost +" | tee -a /etc/profile

  - name: Kali | Create user auditor
    shell: useradd -m auditor; usermod -aG adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev,wireshark,bluetooth,scanner,kaboxer auditor; chsh -s /bin/bash auditor

  - name: Kali | Make auditor a sudoers without password
    shell: echo "auditor ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/auditor

  - name: Kali | Change auditor password
    ansible.builtin.user:
      name: "auditor"
      state: present
      password: "$6$LbY1vAN9zLT1RUNA$CEe2wmcCx3r/mmq/96LgGXvK3vCQjFzT0RUjSZDOuetXwmJV01UPv4n0xoI0JJuGukxE6KC0F2kCNzfWazSyG0"

  - name: Kali | Install "python3-impacket" package
    ansible.builtin.apt:
      name: python3-impacket
      update_cache: yes

  - name: Kali | Install "remmina" package
    ansible.builtin.apt:
      name: remmina

  - name: Kali | Install "Apache2" package
    ansible.builtin.apt:
      name: apache2

  - name: Kali | Update /var/www/htlm privileges
    ansible.builtin.file:
      path: /var/www/html
      group: auditor
      mode: u=rwx,g=rwx,o=r

  - name: Kali | Start service Apache2
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes

  - name: Kali | Install "samba" package
    ansible.builtin.apt:
      name: samba

  - name: Kali | Backup samba config file
    shell: cp /etc/samba/smb.conf /etc/samba/smb.conf.bak

  - name: Kali | Update samba config file
    template:
      src: "files/smb.conf"
      dest: "/etc/samba/smb.conf"

  - name: Kali | Start service Samba
    ansible.builtin.service:
      name: smbd
      state: started
      enabled: yes

  - name: Kali | Upload Interfaces
    template:
      src: "files/interfaces"
      dest: "/etc/network/interfaces"
      
  - name: Kali | Upload Wired Connection 1
    template:
      src: "files/WiredConnection1"
      dest: "/etc/NetworkManager/system-connections/Wired\ connection\ 1"

  - name: Kali | Reboot the machine
    reboot:
      reboot_timeout: 100