---
# https://blog.51sec.org/2023/01/how-to-upgrade-windows-10-evaluation.html
  - name: Upload Windows Workstation Activation File
    ansible.windows.win_copy:
      src: "../files/skus-Windows-10.zip"
      dest: "C:\\Users\\vagrant\\Downloads\\skus-Windows-10.zip"
  
  - name: Unzip Activation File
    community.windows.win_unzip:
      src: C:\\Users\\vagrant\\Downloads\\skus-Windows-10.zip
      dest: C:\Windows\System32\spp\tokens\skus\

  - name: Upload Windows Activation Script
    ansible.windows.win_copy:
      src: "../files/activate_wks.bat"
      dest: "C:\\Users\\vagrant\\Downloads\\activate_wks.bat" 

  - name: Execute Windows Activation Script
    win_command: "C:\\Users\\vagrant\\Downloads\\activate_wks.bat"