---
- hosts: goku
  gather_facts: True
  vars:
    dc_hostname: goku
    domain_Name: capsulecorp.local
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    host_ip: "10.10.10.5"
    dns_server: "127.0.0.1"
    ethernet_adapter: "Ethernet"
  # tasks:
  # - name: Activate windows
  #   win_shell: cscript slmgr.vbs /rearm
  #   args:
  #     chdir: C:\Windows\System32\
    
  roles:
    - role: disable_rtm
    - role: promotedc
    - role: windows_ip
    - role: activate_windows_srv
